01 Numpy In Python

In [1]:
! pip install numpy

In [3]:
import numpy as np

arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) 

array([[1, 2, 3, 4, 5]])

In [4]:
arr2=np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [5]:
#2d array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [6]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
# identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Attributes of Numpy Array
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape)  
print("Number of dimensions:", arr.ndim)  
print("Size (number of elements):", arr.size)  
print("Data type:", arr.dtype) 
print("Item size (in bytes):", arr.itemsize)  

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int32
Item size (in bytes): 4


In [10]:
# Numpy Vectorized Operation -  Element Wise 
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition:", arr1+arr2)
print("Substraction:", arr1-arr2)
print("Multiplication:", arr1 * arr2)
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [11]:
# Universal Function
arr=np.array([2,3,4,5,6])

print(np.sqrt(arr)) # square root
print(np.exp(arr)) # Exponential
print(np.sin(arr)) # Sin
print(np.log(arr)) # natural log

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [4]:
# array slicing and Indexing

arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [6]:
print(arr[2][0])
print(arr[0:2,2:])

9
[[3 4]
 [7 8]]


In [22]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [7]:
# Modify array elements
arr[0,0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [8]:
arr[1:]=100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [9]:
# statistical concepts--Normalization
data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [12]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

mean = np.mean(data)
print("Mean:", mean)

median = np.median(data)
print("Median:", median)

std_dev = np.std(data)
print("Standard Deviation:", std_dev)

variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [11]:
# Logical operation
data=np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]

array([5, 6, 7, 8])